config/routes.rb
Rails.application.routes.draw do
  
  root 'login#login'
  get 'signup' => 'login#signup'

  get 'login/login'
  get 'login/signup' => 'signup#signup'

  post 'check' => 'login#check'
  post 'dosignup' => 'login#dosignup'

  resources :usuarios

end

app/models/usuario.rb
require 'bcrypt'

class Usuario < ActiveRecord::Base

    validates :usuario  , null: false, uniqueness: true 
    validates :password , null: false 
    validates :alias    , null: false, uniqueness: true 
    validates :email    , null: false, uniqueness: true

    has_secure_password

    #def password
    #  @password ||= BCrypt::Password.new(password_hash)
    #end

    # def password=(new_password)
      # puts "ME llamaaaaaaron"
      # @password = BCrypt::Password.create(new_password)
      # puts "Este es el password que paso #{@password}"
      # self.password = @password
    # end

    def passwordMatches?(pass)
      @user = User.new(params[:user])
      @user.password_digest == BCrypt::Password.create(pass)
    end

    def authenticate_safely(usuario, password)
        where("usuario = ? AND password = ?", usuario, password).first
    end 

    def create
      @user = User.new(params[:user])
      @user.password = BCrypt::Password.create(params[:password])
      @user.save!
    end

    def forgot_password
      @user = User.find_by_email(params[:email])
      random_password = Array.new(10).map { (65 + rand(58)).chr }.join
      @user.password = random_password
      @user.save!
      Mailer.create_and_deliver_password_change(@user, random_password)
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  

  def login
    @usuario = Usuario.new
  end

  def check
    p = login_params
    existe = Usuario.authenticate_safely(p[:usuario],p[:password])
   

    if existe
      redirect_to "/lista", :usuario => p[:usuario]
    elsif !existe
      redirect_to "/"
    end

    
  end

  def signup
    @usuario = Usuario.new
  end

  def dosignup

    u = Usuario.new(usuario_params)
    
    if (u.valid? and u.new_record?)
      u.save
      redirect_to "/"
    else
      redirect_to "/signup"
    end
  end

  def usuario_params
    params.require(:usuario).permit(:usuario, :password, :alias, :email)
  end

  def login_params
    params.require(:usuario).permit(:usuario, :password)
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end


  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      puts "ESTO ES EN usuario_params#{params}"

      if params.has_key?(:login)
        params[:login][:tipo] = "login"
        params.require(:login).permit(:usuario, :password,:tipo)
      elsif params.has_key?(:usuario)
        params.require(:usuario).permit(:usuario, :password, :alias, :email)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <!-- Basic Page Needs
  ================================================== -->
    <meta charset="utf-8">
    <title>zBasicH001 Free Html5 Responsive Template</title>
    <meta name="description" content="Free Html5 Templates and Free Responsive Themes Designed by Kimmy | zerotheme.com">
    <meta name="author" content="www.zerotheme.com">
    
    <!-- Mobile Specific Metas
  ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- CSS
  ================================================== -->
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag "responsive" %>
    <%= stylesheet_link_tag "zerogrid" %>
    
    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="js/html5.js"></script>
        <script src="js/css3-mediaqueries.js"></script>
    <![endif]-->
    

    <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<!--------------Header--------------->
<header>
    <div class="wrap-header zerogrid">
        <div id="logo"><a href="#"><%= image_tag("logo.png") %></a></div>
            
        <div id="search">
            <div class="button-search"></div>
            <input type="text" value="Search..." onfocus="if (this.value == &#39;Search...&#39;) {this.value = &#39;&#39;;}" onblur="if (this.value == &#39;&#39;) {this.value = &#39;Search...&#39;;}">
        </div>
    </div>
</header>


<!--------------Content--------------->
<section id="content">
    <div class="wrap-content zerogrid">
        <div class="row block01">
            <div class="col-full">
                <div class="wrap-col">
                    <h2>Bienvenido al sistema de lista de San Antonio / Los     teques !</h2>
                    
                    

                </div>
            </div>
        </div>
        
       
    </div>
</section>
<!--------------Footer--------------->
<footer>
    <div class="wrap-footer">
        <div class="copyright">
            <p>Copyright © 2012 - <a href="http://www.zerotheme.com" target="_blank">Free Basic Html5 Responsive Templates</a> by Zerotheme.com</p>
        </div>
    </div>
</footer>

</body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aplicacion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/_base.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
    <%= yield(:head) %>
    <!-- Basic Page Needs
  ================================================== -->
    <meta charset="utf-8">
    <title>zBasicH001 Free Html5 Responsive Template</title>
    <meta name="description" content="Free Html5 Templates and Free Responsive Themes Designed by Kimmy | zerotheme.com">
    <meta name="author" content="www.zerotheme.com">
    
    <!-- Mobile Specific Metas
  ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- CSS
  ================================================== -->
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag "responsive" %>
    <%= stylesheet_link_tag "zerogrid" %>
    
    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="js/html5.js"></script>
        <script src="js/css3-mediaqueries.js"></script>
    <![endif]-->
    

    <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<header>
    <div class="wrap-header zerogrid">
        <div id="logo"><a href="#"><%= image_tag("logo.png") %></a></div>
        <!-- 
        <div id="search">
            <div class="button-search"></div>
            <input type="text" value="Search..." onfocus="if (this.value == &#39;Search...&#39;) {this.value = &#39;&#39;;}" onblur="if (this.value == &#39;&#39;) {this.value = &#39;Search...&#39;;}">
        </div> -->
    </div>
</header>



<section id="content">
    <div class="wrap-content zerogrid">
        <div class="row block01">
            <div class="col-full">
                <div class="wrap-col">
                    
                    <div class="contenido">
                        <h2>Bienvenido al Sistema de lista de San Antonio / Los     Teques!</h2>
                        
                        <%= yield :contenido %>
                    </div>

                </div>
            </div>
        </div>
        
       
    </div>

</section>

<footer>
    <%= yield(:footer) %>
    <div class="wrap-footer">
        <div class="copyright">
            <p>Copyright © 2012 - <a href="http://www.zerotheme.com" target="_blank">Free Basic Html5 Responsive Templates</a> by Zerotheme.com</p>
        </div>
    </div>
</footer>

</body></html>

app/views/login/login.html.erb
<% content_for :contenido do %>

    <%= form_for(@usuario,url: 'check') do |f| %>
      <% if @usuario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

          <ul>
          <% @usuario.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :usuario %><br>
        <%= f.text_field :usuario %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>

      <div class="actions">
        <%= f.submit "Log me in" %>
      </div>

      <%= link_to "Sign up", 'signup' %>
<% end %>

    
<%end%>


<%= render 'base' %>

app/views/login/signup.html.erb
<% content_for :contenido do %>

    <%= form_for(@usuario,url: 'dosignup') do |f| %>
      <% if @usuario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

          <ul>
          <% @usuario.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :usuario %><br>
        <%= f.text_field :usuario %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :alias %><br>
        <%= f.text_field :alias %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div class="actions">
        <%= f.submit "Registrarme" %>
      </div>
    <% end %>




<%end%>

<%= render 'base' %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Password</th>
      <th>Alias</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.usuario %></td>
        <td><%= usuario.password %></td>
        <td><%= usuario.alias %></td>
        <td><%= usuario.email %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @usuario.usuario %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usuario.password %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @usuario.alias %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>